### ISSUE TITLE
Command line option for bundlesPath is outdated

### ISSUE THREAD

**Issue by booc0mtaco** [bitovi/steal-tools#138]
the documentation states that you can use `--bundlesPath` to tell steal where the built files will go, but the command line help mentions `--dist-dir` instead. the options for the command line should be updated to reflect:

- the current option name (`--bundlesPath`)
- the default value used (`dist/bundles` instead of the current `dist`)
- internal variable names, reflecting these options to avoid confusion

Additionally, an example of this option being used might be helpful.

REF: https://github.com/bitovi/steal-tools/blob/master/bin/steal#L64 (96a152929e985bc3be39d68ffdc952508a30ed8c)

**Comment by matthewp** [comment]
I should update this before release.
