### ISSUE TITLE
exports ignore is not normalized

### ISSUE THREAD

**Issue by matthewp** [bitovi/steal-tools#182]
Needs to be so users can ignore npm modules.

**Comment by justinbmeyer** [comment]
But it works with regular expressions. I'm wondering if normalization is wrong, but reverse normalize is right.  Perhaps not.

**Comment by matthewp** [comment]
We can't really do a full denormalization so if we want to support things like `main: "app/"` we have to do normalization. Alternatively we could denpm the module names and put them into a quasi-normalized state like `can/component/component`.

**Comment by matthewp** [comment]
I think denpm-ing the graph might be the way to go.  We can support System.main normalization and then just denpm afterwards.
