### ISSUE TITLE
Generated file names for bundles can exceed file system limit

### ISSUE THREAD

**Issue by asavoy** [bitovi/steal-tools#47]
I tried updating a large project to test the latest Steal and discovered the build won't complete because the filename generated for a widely shared bundle is too long for the file system. 

This is the same issue that I proposed a pull-request on in legacy StealJS in https://github.com/bitovi/steal/pull/170 - NOTE: GitHub seems to have mangled that page with history from a separate issue. The relevant comments are [Justin's](https://github.com/justinbmeyer) and [my response](https://github.com/bitovi/steal/pull/170#issuecomment-26483421).

In that PR I suggest taking truncating long file names and appending a hash, which I think is still reasonable.

**Comment by matthewp** [comment]
Closed by #47
