### ISSUE TITLE
Names generated for main bundles may override one another

### ISSUE THREAD

**Issue by asavoy** [bitovi/steal-tools#52]
When building an app with several main modules, the main module's filename is used as the name for its bundle filename. Since all bundles are put into one folder, it's possible for one to override another.

Take a hypothetical app that builds two main modules, `users/edit/edit` and `tasks/edit/edit`:

1. `tasks/edit/edit.js` is built into bundle `dist/bundles/edit.js`
2. `users/edit/edit.js` is built into bundle `dist/bundles/edit.js`, overriding the first bundle.

Multi-build in legacy-steal avoided this by naming the bundle `production.js` and putting in the same directory as the originating bundle. (But I do prefer this new behavior of keeping all production files in one `dist` folder, though.)

Some potential solutions:

1. Use the relative path of the main bundle, replacing each "/" with "__", for the name of the bundle. That is, `tasks/edit/edit.js` would become `dist/bundles/tasks__edit__edit.js`. This is what I have hacked into my test project.
2. Recreate the paths in the `dist/bundles` folder. That is, `tasks/edit/edit.js` would become `dist/bundles/tasks/edit/edit.js`.

Important to note that I believe StealJS would need to be updated to do the same thing in production mode, too, so whatever naming scheme is used, it must be possible for a client to do also. That means we can't use incrementing numbers or such.

**Comment by matthewp** [comment]
This is fixed now!
