### ISSUE TITLE
stealBuild option system.main issue

### ISSUE THREAD

**Issue by whitecolor** [bitovi/steal-tools#89]
In dev mode main (via script tag attribute) can be defined as for example ```apps/first/``` that will load ```apps/first/first.js```.

In stealBuild options if system.main is defined as ```apps/first/``` will result in build error, so one need to define it there as ```apps/first/first```. 

A little bit inconsistent in my view. Not sure if its needed and correct behaviour.

**Comment by justinbmeyer** [comment]
@joe-crick Once you get the docs working, maybe we can tackle this together.

**Comment by m-mujica** [comment]
I'll take this one. :cop:

**Comment by matthewp** [comment]
I need this for https://github.com/bitovi/steal-tools/issues/168 so I'm taking it.

**Comment by m-mujica** [comment]
![tumblr_m9s72v0ukt1ro2xth](https://cloud.githubusercontent.com/assets/724877/6381892/66c76d0c-bd23-11e4-95e6-e36b2b13a891.gif)

**Comment by matthewp** [comment]
Closed by #169
